### PR TITLE
Make fieldNameMapper a partial function, so that when you rename coup…

### PR DESCRIPTION
**Pull request by jozic**
…le fields, you don't need provide a default case

### CODE REVIEW

**Comment by jozic** [comment]
I guess an alternative can be a second constructor with a partial function, so it will be at least source compatible

**Comment by plokhotnyuk** [comment]
@jozic Hi, Eugene!

Thanks for your feedback and PR! Just one note, to skip binary compatibility check you can increase a version number from 0.51.5 to 0.52.0.

Also, I think that the `adtLeafClassNameMapper` function also worth to be refactored as `PartialFunction`.

Configuration for derivation could be refactored for better and handy API definitely. [Here](https://github.com/plokhotnyuk/jsoniter-scala/issues/238) is a placeholder issue for that.

**Comment by jozic** [comment]
@plokhotnyuk thanks for review!
I will try to address your comments soon

**Comment by jozic** [comment]
@plokhotnyuk Andriy, I'm not sure that `adtLeafClassNameMapper` is also need to be a `PartialFunction` as in most cases you still want to strip off package name and use simple names even if you remap it, like in the test `"serialize and deserialize ADTs using custom values of the discriminator field"` 

```scala
      verifySerDeser(make[List[Base]](CodecMakerConfig(adtLeafClassNameMapper = { case x => JsonCodecMaker.simpleClassName(x) match {
        case "A" => "X"
        case "B" => "Y"
      }}, skipUnexpectedFields = false)),
      List(A(B("x")), B("x")), """[{"type":"X","b":{"c":"x"}},{"type":"Y","c":"x"}]""")
    }
```

doesn't look better then

original

```scala
      verifySerDeser(make[List[Base]](CodecMakerConfig(adtLeafClassNameMapper = x => JsonCodecMaker.simpleClassName(x) match {
        case "A" => "X"
        case "B" => "Y"
      }, skipUnexpectedFields = false)),
```

I can imagine scenario where you have some subtypes which you don't want to rename, let's say 

```scala
      sealed abstract class Base extends Product with Serializable

      final case class A(b: B) extends Base

      final case class B(c: String) extends Base

      final case class Z(i: Int) extends Base
```
then if you want to rename A to X and B to Y, you have following options

in case when `adtLeafClassNameMapper` is a `Function`

```scala
      verifySerDeser(make[List[Base]](CodecMakerConfig(adtLeafClassNameMapper = x => JsonCodecMaker.simpleClassName(x) match {
        case "A" => "X"
        case "B" => "Y"
        case other => other
      }, skipUnexpectedFields = false)),
```

in case when `adtLeafClassNameMapper` is a `PartialFunction`
you get almost same, but slightly more verbose 
```scala
      verifySerDeser(make[List[Base]](CodecMakerConfig(adtLeafClassNameMapper = { case x => JsonCodecMaker.simpleClassName(x) match {
        case "A" => "X"
        case "B" => "Y"
        case other => other
      }}, skipUnexpectedFields = false)),
```

or this, which is most likely less efficient because of multiple evaluations of simple name
```scala
      verifySerDeser(make[List[Base]](CodecMakerConfig(adtLeafClassNameMapper = {
        case n if JsonCodecMaker.simpleClassName(n) == "A" => "X"
        case n if JsonCodecMaker.simpleClassName(n) == "B" => "Y"
        case other => JsonCodecMaker.simpleClassName(other)
      }, skipUnexpectedFields = false)),
```

I'm happy to convert `adtLeafClassNameMapper` to a `PartialFunction`, but doesn't look like we will gain much. WDYT?

**Comment by plokhotnyuk** [comment]
@jozic Thanks for your investigation! 

I'm going to merge your  PR and release a new version today...

**Pull request merged**
