### PR TITLE
contribute upickle codec

### PR DESCRIPTION
**Pull request by jam01**
Here we go! 

I tried to configure the upickle crossProject, but not very familiar with sbt to be honest. 

I also took a look at the tests, but that I wasn't sure where/how to start. Here are [my tests](https://github.com/jam01/json-schema/tree/0.1.0/shared/src/test/scala/upickle/jsoniter).

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
@jam01 Thank you, Jose!

You can add your tests as is using Jupiter dependency at least for JVM sub-project. Later I will convert them to scala-test to be runnable on all platforms.

**Comment by jam01** [comment]
Added the tests. Hoping they run on CI, not sure if JUnit5 requires further setup in sbt

**Comment by plokhotnyuk** [comment]
@jam01 Could you please fetch upstream & rebase to pick support of Scala Native 0.5?

**Comment by jam01** [comment]
Fixed the ujson dependency to the suffix can be replaced by the build framework. Jupiter will continue to fail though.

**Comment by plokhotnyuk** [comment]
Please try `%%` instead of `%%%` for jupiter.

**Comment by jam01** [comment]
Just realized I probably should've done a `readLong` and then checked for validity instead of `readBigInt` since `Long` is probably gonna be the common case

**Comment by plokhotnyuk** [comment]
A better option would be adding parsing of `java.lang.Number` in the `JsonReader` in a most efficient way to avoid redundant scanning or exception handling. That could be reused in the `jsoniter-scala-circe` module and for other applications that parse to some JSON AST.

**Comment by plokhotnyuk** [comment]
There are a couple unit test compilation errors yet:
```
/home/runner/work/jsoniter-scala/jsoniter-scala/jsoniter-scala-upickle/jvm/src/test/scala/upickle/jsoniter/VisitorEncoderTest.scala:5:12: object skyscreamer is not a member of package org
[error] import org.skyscreamer.jsonassert.JSONAssert
[error]            ^
[error] /home/runner/work/jsoniter-scala/jsoniter-scala/jsoniter-scala-upickle/jvm/src/test/scala/upickle/jsoniter/VisitorEncoderTest.scala:25:34: type mismatch;
[error]  found   : upickle.jsoniter.ValueEncoder.type
[error]  required: com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec[ujson.Arr]
[error] Note: ujson.Value >: ujson.Arr (and upickle.jsoniter.ValueEncoder.type <: upickle.jsoniter.VisitorEncoder[ujson.Value]), but trait JsonValueCodec is invariant in type A.
[error] You may wish to define A as -A instead. (SLS 4.5)
[error]     val res = writeToString(arr)(ValueEncoder)
[error]                                  ^
[error] /home/runner/work/jsoniter-scala/jsoniter-scala/jsoniter-scala-upickle/jvm/src/test/scala/upickle/jsoniter/VisitorEncoderTest.scala:26:5: not found: value JSONAssert
[error]     JSONAssert.assertEquals(jsonStr, res, true)
[error]     ^
[error] three errors found
```

**Comment by jam01** [comment]
fixing the jsonassert dependency. The invariant error is strange, because it compiles and passes in my project... :thinking:

**Comment by plokhotnyuk** [comment]
I've changed the base branch to merge and see locally

**Pull request merged**
